apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-homeserver
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/secure-backends: "true"
spec:
  tls:
  - hosts:
    - nganfamily.com
    - covid19.nganfamily.com
    - loadtest.nganfamily.com
    - ping.nganfamily.com
    secretName: letsencrypt-prod
  rules:
    - host: nganfamily.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ping-server
                port:
                  number: 8000
    - host: covid19.nganfamily.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: covid19-server
                port:
                  number: 8080
    - host: loadtest.nganfamily.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loadtest
                port:
                  number: 8004
    - host: ping.nganfamily.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ping-server
                port:
                  number: 8000