apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: loadtest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadtest
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 1
        periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadtest
  name: loadtest
spec:
  replicas: 4
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
      name: loadtest
    spec:
      containers:
      - name: loadtest
        image: pngan/aspnetcore-kubernetes:1003
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "200m"
            memory: "50Mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loadtest
  name: loadtest
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: loadtest