---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secrets-test
  name: secrets-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-test
  template:
    metadata:
      labels:
        app: secrets-test
    spec:
      containers:
      - command: ["/bin/sh"]
        args: ["-c", "echo $OVH_ENDPOINT; echo $OVH_APPLICATION_KEY; echo $OVH_APPLICATION_SECRET;\
            \ echo $OVH_CONSUMER_KEY; sleep infinity"]
        image: alpine:latest
        name: secrets-test
        resources:
          limits:
            memory: 64Mi
            cpu: 500m
        env:
        - name: OVH_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: ovh-secrets
              key: endpoint
        - name: OVH_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: ovh-secrets
              key: application_key
        - name: OVH_APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              name: ovh-secrets
              key: application_secret
        - name: OVH_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: ovh-secrets
              key: consumer_key
